name: Hexo Build & Deploy - Private to Public

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Prepare Node env
        uses: actions/setup-node@v3
        with:
          node-version: 18
  
      - name: Hexo
        run: |
          npm i -g hexo-cli
          npm i
          hexo clean && hexo g
  
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: Soulter/806Blogs
          branch: master # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          single-commit: true
          commit-message: "Deploy by source"
